//Code here is for connecting to motors, I had to type up this whole code sooooo... I have to double check that this works
#pragma config(Motor, port1,		leftMotor, tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor, port10,		leftMotor, tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor, port7,		arm, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port6,		claw, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard.... not.... yet

//Function declarations - This has to be done before putting the code in the functions
//Here's what a function declaration looks like
//RETURN_TYPE(or void if you're not returning any values) FUNCTION_NAME(PARAMETERS);
void move(int speed);
void openClaw();
void closeClaw();
void raiseArm(int ms);
void lowerArm(int ms);
